name: Deploy Dev Nginx

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy config and deploy script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            nginx-config/polybot-dev.conf
            scripts/deploy_nginx.sh
          target: /home/ubuntu/

      - name: Prepare config and restore certs on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/conf.d /home/ubuntu/certs
            mv /home/ubuntu/polybot-dev.conf /home/ubuntu/conf.d/
            echo "${{ secrets.NGINX_KEY_B64 }}" | base64 -d > /home/ubuntu/certs/server.key
            echo "${{ secrets.NGINX_CRT_B64 }}" | base64 -d > /home/ubuntu/certs/server.crt
            chmod +x /home/ubuntu/deploy_nginx.sh
            /home/ubuntu/deploy_nginx.sh
