name: Deploy Nginx Container to Dev

on:
  push:
    paths:
      - "nginx-config/polybot-dev.conf"
      - "scripts/deploy_nginx.sh"
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Ensure target directory exists on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/conf.d"

    - name: Copy Nginx config and deploy script to EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no \
          nginx-config/polybot-dev.conf \
          ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/conf.d/

        scp -i key.pem -o StrictHostKeyChecking=no \
          scripts/deploy_nginx_container.sh \
          ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

    - name: Run deploy script on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          chmod +x /home/ubuntu/deploy_nginx.sh
          /home/ubuntu/deploy_nginx.sh
        EOF
