apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: merryshalabi/polybot:latest
        ports:
        - containerPort: 5000
